### ISSUE TITLE
Deployment according to the docs is not working

### ISSUE THREAD

**Issue by linkvt** [kubernetes-csi/csi-driver-nvmf#10]
Hi,

first of all thanks for this project, I really like the idea to abstract nvme of mounting with a CSI plugin!

I'm not sure if I did something wrong or if it is just an error in the examples or the documentation, but after deploying everything this plugin does not work for me - the mounting never happens.

Few possible errors in the docs I found were
- not matching storage class name in examples
  - storage class https://github.com/kubernetes-csi/csi-driver-nvmf/blob/master/examples/kubernetes/example/storageclass.yaml#L4
  - pv https://github.com/kubernetes-csi/csi-driver-nvmf/blob/master/examples/kubernetes/example/pv.yaml#L6
- `NVMf` CSI driver instead of `csi.nvmf.com` in PV exampe https://github.com/kubernetes-csi/csi-driver-nvmf/blob/master/examples/kubernetes/example/pv.yaml#L12
- `--attrib` parameter of the current https://github.com/rexray/gocsi/tree/master/csc does not exist anymore
Not sure if there is more or if the documentation is even complete?

I basically used the files from `deploy/kubernetes` to deploy everything on vanilla k8s 1.23, the CSI driver also logs out that the registration was successful and my PV contains the `csi.driver` field as the registration output showed.
The PVC is of course also bound to the PV and I'm pretty confident in my k8s basics :smiley: but if you need more infos I will happily provide everything!

Is it just me or did I miss something? Does this csi driver work for anyone else as documented?

Thanks in advance!
Vincent

**Comment by MeinhardZhou** [comment]
Hi, @linkvt,

Thanks for reporting the issue. The possible errors you mentioned do exist.

I will fix the example YAML files and refresh the README (about settings of NVMf Kernel Target) in the next few days. Meanwhile, during my test, I found that there is a path error in `fabrics.c`.

**Comment by MeinhardZhou** [comment]
@linkvt When you use the pv.yaml of example, you need to update `volumeAttributes` to your attributes

**Comment by linkvt** [comment]
Hi @MeinhardZhou ,
thanks for the quick resolution of these issues!
 I will be able to test the current version again in the next few days and give feedback.
