### ISSUE TITLE
when will the NVMe-oF Controller/Agent be added?

### ISSUE THREAD

**Issue by huang339** [kubernetes-csi/csi-driver-nvmf#9]
when will the NVMe-oF Controller/Agent be added?

**Comment by MeinhardZhou** [comment]
NVMe-oF controller/agent is not a part of csi-driver-nvmf, it's an additional component, and it is expected to be completed in Q4 this year in another repo.

**Comment by huang339** [comment]
I hope NVMe-oF controller/agent will be added earlier enen it is not very well, more people can join together to make it better
